apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster
spec:
  instances: 3

  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true
        kubectl get secret cluster-app -n db \
  -o jsonpath="{.data.pgpass}" | base64 -d